<a href="https://colab.research.google.com/github/sairam91334/478-sigma-day3/blob/main/17_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
j=[4,6,2,8,9]
j

[4, 6, 2, 8, 9]

In [ ]:
import numpy as np

d = np.array([1, 2, 3, 4, 5, 6])

w = d.reshape(3, 2)

In [ ]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [ ]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [ ]:
range(-10,1)

range(-10, 1)

In [ ]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [ ]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [ ]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [ ]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
for i in range(5,50,5):
  print('Data,i')

Data,i
Data,i
Data,i
Data,i
Data,i
Data,i
Data,i
Data,i
Data,i


In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [ ]:
y=[]
x=[]
for i in range(len(j)):
  if i%2==0:
    y.append(j[i])
  else:
    x.append(j[i])

In [19]:
np.random.normal(10,2,(7,4))

array([[ 8.51084004, 12.11567626,  8.31454781, 13.90305515],
       [ 7.65595788, 12.92310197, 11.14717952, 12.55958451],
       [10.45174701, 12.6580322 ,  8.73362077,  9.66502465],
       [ 7.95852191, 11.57944165,  6.90596265, 10.5778117 ],
       [10.22015692, 11.96295786,  9.81491501,  6.81151642],
       [ 7.49168061, 11.95511611,  8.70886875, 11.44531667],
       [ 7.45588606, 13.45059905, 10.35319179,  6.26026176]])

In [20]:
np.random.randint(35,86)

69

In [21]:
np.random.randint(35,86,10)

array([60, 38, 47, 57, 39, 74, 55, 69, 47, 43])