<a href="https://colab.research.google.com/github/sairam91334/478-sigma-day3/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [2,12,23,10,89]])
print(arr)
print('0th element on 2nd row: ', arr[1,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2 12 23 10 89]]
0th element on 2nd row:  9


In [2]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [2, 12, 23, 10, 89]])
print(arr)
print(arr[1:3, 1:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2 12 23 10 89]]
[[ 7  8  9 10]
 [12 23 10 89]]


In [3]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[1, 1, 2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
print(arr[1:5:2])

[2 4]


In [5]:
import pandas as pd
sales_data = {
'TransactionID': [1, 2, 3, 4, 5],
'CustomerID': [101, 102, 103, 104, 105],
'Amount': [250, 300, 40, 50, 600],
'Date': ['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05']
}
customer_data = {
'CustomerID': [101, 102, 103, 104],
'CustomerName': ['Alice', 'Bob', 'Charlie', 'David'],
'Age': [30, 35, 40, 25],
'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
sales_df = pd.DataFrame(sales_data)
customer_df = pd.DataFrame(customer_data)
print("Sales Department:")
print(sales_df.head())

Sales Department:
   TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103      40  2025-01-03
3              4         104      50  2025-01-04
4              5         105     600  2025-01-05


In [6]:
import pandas as pd
data = {
    "Name": ["John", "Alice", "Bob", "Diana"],
    "Age": [28, 34, 23, 29],
    "Department": ["HR", "IT", "Marketing", "Finance"],
    "Salary": [45000, 60000, 35000, 50000]
}
Marks = {
    "Name":["vedith","Rohith"],
    "AI":[12,15],
    "ML":[15,14]
}
df = pd.DataFrame(data)
df1=pd.DataFrame(Marks)
print(df)
print(df1)

    Name  Age Department  Salary
0   John   28         HR   45000
1  Alice   34         IT   60000
2    Bob   23  Marketing   35000
3  Diana   29    Finance   50000
     Name  AI  ML
0  vedith  12  15
1  Rohith  15  14


In [7]:
import pandas as pd
sales_data = {
'TransactionID': [1, 2, 3, 4, 5],
'CustomerID': [101, 102, 103, 104, 105],
'Amount': [250, 300, 40, 50, 600],
'Date': ['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05']
}
customer_data = {
'CustomerID': [101, 102, 103, 104],
'CustomerName': ['Alice', 'Bob', 'Charlie', 'David'],
'Age': [30, 35, 40, 25],
'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
sales_df = pd.DataFrame(sales_data)
customer_df = pd.DataFrame(customer_data)
print("Sales Department:")
print(sales_df.head())

#1. Exploring the datatset (using shape and describe)
print("\nShape of the sales data:", sales_df.shape)
print("\nSales data statistics:")
print(sales_df.describe())
print("Sales Dataframe", sales_df)
print("customer_df", customer_df)

#2. merging the data (Sales with Customer
merged_df = pd.merge(sales_df, customer_df, on='CustomerID', how='inner')
print("\nMerged DataFrame:")
print(merged_df)

#3. Accessing data using 'loc' and 'iloc'
print("\nAccess data using 'loc' (row 1):")
print(merged_df.loc[1])
print("\nAccess data suing 'iloc' (row 2):")
print(merged_df.iloc[2])

Sales Department:
   TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103      40  2025-01-03
3              4         104      50  2025-01-04
4              5         105     600  2025-01-05

Shape of the sales data: (5, 4)

Sales data statistics:
       TransactionID  CustomerID      Amount
count       5.000000    5.000000    5.000000
mean        3.000000  103.000000  248.000000
std         1.581139    1.581139  228.626333
min         1.000000  101.000000   40.000000
25%         2.000000  102.000000   50.000000
50%         3.000000  103.000000  250.000000
75%         4.000000  104.000000  300.000000
max         5.000000  105.000000  600.000000
Sales Dataframe    TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103      40  2025-01-03
3             